name: Node.js CI
on:
  push:
    branches: [ "main" ]
jobs:

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd java-deploy-test
            echo "in the directory now"
            git pull
            docker build --no-cache -t java:latest .
            docker stop java || true
            docker rm java || true
            docker run -d --name java \
              -p 8185:8185 \
              java:latest
            
